services:
  engine:
    image: umarkhorami/invoice-engine:latest
    container_name: engine
    restart: unless-stopped
    ports:
      # Maps external port 8080 to internal port 3000
      - "8080:3000"
    volumes:
      - ./server_data:/app/data
    environment:
      - RUNNING_IN_DOCKER=true
      # Uncomment and set this if placing behind a reverse proxy/Cloudflare Tunnel
      # - APP_ORIGIN=https://invoices.yourdomain.com

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
